// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVBZNkmHmbMfBKRUm6m92revQA63zNGt4',
    appId: '1:113166009025:web:bcdded748ad1c3a57a4a40',
    messagingSenderId: '113166009025',
    projectId: 'medicine-app-fea84',
    authDomain: 'medicine-app-fea84.firebaseapp.com',
    storageBucket: 'medicine-app-fea84.firebasestorage.app',
    measurementId: 'G-P9BMCP9MG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6wmUBYW898-yeTpHHEtlUHAlfy-lCqVY',
    appId: '1:113166009025:android:40c960b08e1dbc647a4a40',
    messagingSenderId: '113166009025',
    projectId: 'medicine-app-fea84',
    storageBucket: 'medicine-app-fea84.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNkI4UnlnJO7gjxXpjZMkLj9iC8QUwnrI',
    appId: '1:113166009025:ios:be5edf89c099ba037a4a40',
    messagingSenderId: '113166009025',
    projectId: 'medicine-app-fea84',
    storageBucket: 'medicine-app-fea84.firebasestorage.app',
    iosBundleId: 'com.example.medicineApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNkI4UnlnJO7gjxXpjZMkLj9iC8QUwnrI',
    appId: '1:113166009025:ios:be5edf89c099ba037a4a40',
    messagingSenderId: '113166009025',
    projectId: 'medicine-app-fea84',
    storageBucket: 'medicine-app-fea84.firebasestorage.app',
    iosBundleId: 'com.example.medicineApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVBZNkmHmbMfBKRUm6m92revQA63zNGt4',
    appId: '1:113166009025:web:6f319dadb79d4e387a4a40',
    messagingSenderId: '113166009025',
    projectId: 'medicine-app-fea84',
    authDomain: 'medicine-app-fea84.firebaseapp.com',
    storageBucket: 'medicine-app-fea84.firebasestorage.app',
    measurementId: 'G-8WW29BL7JL',
  );

}